=head1 NAME

ren_ext ("rename extended") renames (recursively) files and directories using 
regexps.

=head1 DESCRIPTION

this program lets you rename files or directories by using regular expressions. 

it includes a check, whether a target filename already exists or whether several 
target filenames are same, and prints a warning in such cases.

=head1 MOVED

moved to gitlab: https://gitlab.com/wp-seth/ren_ext
